### ISSUE TITLE
Error during publish

### ISSUE THREAD

**Issue by calebgab** [InternetExplorer/Enterprise-Mode-Data-Collection-Sample#2]
When I'm publishing the code I get the following error. Looking at the files from the download (both on my machine and here on GitHub) I don't even see the file. Can someone help please?

Cheers

Copying file Content\themes\base\jquery-ui.css to obj\Release\Package\PackageTmp\Content\themes\base\jquery-ui.css failed. Could not find file 'Content\themes\base\jquery-ui.css'.		0	0	PhoneHomeSample

**Comment by anothervictim** [comment]
Same issue. Please respond. Thanks!

**Comment by prabsc** [comment]
This should be fixed in the latest commits.
